SELECT USER_ID, Product_ID, SUM(QUANTITY_SOLD) AS TotalQuantity FROM SALE_PROJECT AS S GROUP BY USER_ID, Product_ID
HAVING 
SUM(QUANTITY_SOLD) = (SELECT MAX(TotalQuantity)FROM (SELECT SUM(QUANTITY_SOLD) AS TotalQuantity
 FROM Sale_PROJECT AS innerSales WHERE innerSales.USER_ID = S.USER_ID GROUP BY Product_ID) AS subquery);