SELECT
    s.USER_ID,
    COUNT(s.PRODUCT_ID) AS TotalOrders,
    SUM(s.SALE_PRICE) AS TotalAmountSpent
FROM
    SALE_PROJECT AS s
JOIN
    USERS_PROJECT AS u ON s.USER_ID = u.USER_ID
JOIN
    GOLD_USER_SIGNUP AS G ON u.USER_ID = G.USER_ID
WHERE
    s.CREATED_DATE < G.SIGNUP_DATE
GROUP BY
    s.USER_ID;