SELECT U.User_ID, COUNT(S.Product_ID) AS OrderCount FROM Users_PROJECT AS U 
JOIN GOLD_USER_SIGNUP AS G ON U.User_ID = G.User_ID
JOIN SALE_PROJECT AS S ON U.User_ID = S.User_ID
WHERE G.Membership = 'GOLD' GROUP BY U.User_ID;